org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.48
neo_version_range=[21.1,)
loader_version_range=[4,)
mod_id=simplelogistic
mod_name=Simple Logistic
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.simplelogistic
mod_authors=Antigravity
mod_description=A TPS friendly proportional pipe network mod.
