name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 25 (Toolchain)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Java 21 (Gradle Runner)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build -x test --info --stacktrace

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleLogistic-${{ github.sha }}
          path: build/libs/*.jar
          if-no-files-found: error
